name: Deploy Flutter Web to Server

on:
  push:
    branches:
      - server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.1

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release
      
      - name: My folder structure
        run: ls


      - name: Clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/koselikh/rujamaharjan.com.np
            rm -rf ./*
      - name: Deploy to server test 1
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SERVER_PORT }}
          strip_components: 2
          source: build/web/*
          target: /home/koselikh/rujamaharjan.com.np
     
     
